name: PyExamples
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.7
  - numpy=1.17.3
  - pandas=0.25.3
  - toml=0.10.0
  - pysimplegui=4.2
  - pip=20.0.2
  - pip:
    - colorama==0.4.1
    - termcolor==1.1.0

